class StudentsController < ApplicationController
  before_action :set_student, only: :show

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def activate
    @student = Student.find(params[:id])
    @student.active = !@student.active
    # THIS IS THE SWITCH - it turns the default inactive student to Active

    @student.save
    redirect_to student_path(@student)

    # https://apidock.com/rails/ActionController/Base/redirect_to

#     redirect_to(options = {}, response_status = {}) protected
# Redirects the browser to the target specified in options. This parameter can take one of three forms:
#
# Hash - The URL will be generated by calling url_for with the options.
# Record - The URL will be generated by calling url_for with the options, which will reference a named URL for that record.
  end


  private

    def set_student
      @student = Student.find(params[:id])
    end
end
